/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DownloadRecord = IDL.Record({
  'occupation' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'invitedBy' : IDL.Text,
  'whatsapp' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'getCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getRecords' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(DownloadRecord)],
      ['query'],
    ),
  'recordDownload' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Int],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DownloadRecord = IDL.Record({
    'occupation' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'invitedBy' : IDL.Text,
    'whatsapp' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'getCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getRecords' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(DownloadRecord)],
        ['query'],
      ),
    'recordDownload' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Int],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };